// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResiPay.DB;

#nullable disable

namespace ResiPay.DB.Migrations
{
    [DbContext(typeof(ResiPayDbContext))]
    partial class ResiPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentUser", b =>
                {
                    b.Property<int>("ApartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ApartmentsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserApartments", "dbo");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("apartment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentBlock")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("block");

                    b.Property<int>("ApartmentFloor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<string>("ApartmentType")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("date")
                        .HasColumnName("insert_date");

                    b.Property<bool>("IsFull")
                        .HasColumnType("boolean")
                        .HasColumnName("is_full");

                    b.Property<bool>("IsRented")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rented");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.ToTable("Apartment", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentBlock = "A",
                            ApartmentFloor = 4,
                            ApartmentNumber = 44,
                            ApartmentType = "2+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7059),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7060)
                        },
                        new
                        {
                            Id = 2,
                            ApartmentBlock = "B",
                            ApartmentFloor = 3,
                            ApartmentNumber = 34,
                            ApartmentType = "1+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7088),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7088)
                        },
                        new
                        {
                            Id = 3,
                            ApartmentBlock = "C",
                            ApartmentFloor = 5,
                            ApartmentNumber = 65,
                            ApartmentType = "3+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7090),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7090)
                        },
                        new
                        {
                            Id = 4,
                            ApartmentBlock = "B",
                            ApartmentFloor = 5,
                            ApartmentNumber = 63,
                            ApartmentType = "2+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7091),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7092)
                        },
                        new
                        {
                            Id = 5,
                            ApartmentBlock = "D",
                            ApartmentFloor = 7,
                            ApartmentNumber = 87,
                            ApartmentType = "1+0",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7093),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7093)
                        },
                        new
                        {
                            Id = 6,
                            ApartmentBlock = "G",
                            ApartmentFloor = 13,
                            ApartmentNumber = 144,
                            ApartmentType = "3+0",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7094),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7094)
                        },
                        new
                        {
                            Id = 7,
                            ApartmentBlock = "E",
                            ApartmentFloor = 6,
                            ApartmentNumber = 78,
                            ApartmentType = "1+0",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7095),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7096)
                        },
                        new
                        {
                            Id = 8,
                            ApartmentBlock = "D",
                            ApartmentFloor = 3,
                            ApartmentNumber = 33,
                            ApartmentType = "1+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7096),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7097)
                        },
                        new
                        {
                            Id = 9,
                            ApartmentBlock = "A",
                            ApartmentFloor = 2,
                            ApartmentNumber = 19,
                            ApartmentType = "3+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7098),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7098)
                        },
                        new
                        {
                            Id = 10,
                            ApartmentBlock = "B",
                            ApartmentFloor = 9,
                            ApartmentNumber = 111,
                            ApartmentType = "2+1",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7099),
                            IsFull = true,
                            IsRented = true,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(7099)
                        });
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("apartment_id");

                    b.Property<decimal>("BillAmount")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("date")
                        .HasColumnName("assign_date");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("payment_status");

                    b.Property<int>("Month")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Bill", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            BillAmount = 300m,
                            BillType = "gas",
                            DueDate = new DateTime(2023, 8, 30, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6979),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6978),
                            IsPaid = false,
                            Month = 9,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6979),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            BillAmount = 220m,
                            BillType = "water",
                            DueDate = new DateTime(2023, 8, 23, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6984),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6984),
                            IsPaid = false,
                            Month = 9,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6984),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 3,
                            BillAmount = 140m,
                            BillType = "electric",
                            DueDate = new DateTime(2023, 8, 17, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6986),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6985),
                            IsPaid = false,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6986),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 3,
                            BillAmount = 50m,
                            BillType = "other",
                            DueDate = new DateTime(2023, 8, 28, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6989),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6988),
                            IsPaid = true,
                            Month = 9,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6988),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 4,
                            BillAmount = 80m,
                            BillType = "electric",
                            DueDate = new DateTime(2023, 8, 17, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6990),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6989),
                            IsPaid = false,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6990),
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 5,
                            BillAmount = 230m,
                            BillType = "electric",
                            DueDate = new DateTime(2023, 8, 13, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6992),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6991),
                            IsPaid = true,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6991),
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            ApartmentId = 6,
                            BillAmount = 600m,
                            BillType = "gas",
                            DueDate = new DateTime(2023, 8, 27, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6993),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6993),
                            IsPaid = false,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6993),
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            ApartmentId = 6,
                            BillAmount = 30m,
                            BillType = "other",
                            DueDate = new DateTime(2023, 8, 12, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6995),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6994),
                            IsPaid = false,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6995),
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            ApartmentId = 6,
                            BillAmount = 80m,
                            BillType = "water",
                            DueDate = new DateTime(2023, 8, 19, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6996),
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6996),
                            IsPaid = false,
                            Month = 8,
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6996),
                            UserId = 6
                        });
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverSurname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("receiver_surname");

                    b.Property<string>("SenderName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderSurname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sender_surname");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("read_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Message", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sayın admin. Geceleri birinci kattan gelen yüksek müzik nedeniyle uyuyamıyoruz. Lütfen gereğini yapın!",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6918),
                            IsDeleted = false,
                            IsRead = false,
                            ReceiverId = 1,
                            Subject = "Müzik gürültüsü",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6919),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Asansördeki elektrik sürekli kopuyor ve tedirgin oluyoruz. Lütfen gereğini yapın",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6921),
                            IsDeleted = false,
                            IsRead = false,
                            ReceiverId = 1,
                            Subject = "Asansör Işığı",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6921),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sayın komşu. Katınızda yarın sabah 9.00-11.00 saatleri arasında boru tadilatı yapılacaktır. Bilginize. Yönetici.",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6922),
                            IsDeleted = false,
                            IsRead = false,
                            ReceiverId = 2,
                            Subject = "Tadilat",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6923),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Sayın yönetici. Son günlerde sitemizde hırsızlık olayları artmıştır. Ailecek tedirgin oluyoruz. Lütfen gereğini yapın.",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6923),
                            IsDeleted = false,
                            IsRead = false,
                            ReceiverId = 1,
                            Subject = "Hırsız sorunu",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6924),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Content = "Sayın yönetici. Çöplerimiz 3 gündür alınmıyor. Lütfen gereğini yapın.",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6924),
                            IsDeleted = false,
                            IsRead = false,
                            ReceiverId = 1,
                            Subject = "Çöpler",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6925),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ResiPay.DB.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("apartment_id");

                    b.Property<string>("CarPlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("identity_number");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("date")
                        .HasColumnName("membership_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("delete_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber");

                    b.ToTable("User", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            Email = "admin@gmail.com",
                            IdentityNumber = "82842683832",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6501),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Beyza",
                            Password = "deneme",
                            PhoneNumber = "0555 555 55 55",
                            Status = "Admin",
                            Surname = "Cabuk",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6510)
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            Email = "e.yildirim@gmail.com",
                            IdentityNumber = "34965092008",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6523),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Erkan",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 56",
                            Status = "Resident",
                            Surname = "Yıldırım",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6523)
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 3,
                            Email = "s.yilmaz@gmail.com",
                            IdentityNumber = "78185721324",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6652),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Serkan",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 57",
                            Status = "Resident",
                            Surname = "Yılmaz",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6652)
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 4,
                            Email = "g.aslan@gmail.com",
                            IdentityNumber = "97968823406",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6675),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Gürkan",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 58",
                            Status = "Resident",
                            Surname = "Aslan",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6676)
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 5,
                            Email = "c.aslan@gmail.com",
                            IdentityNumber = "80829170948",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6718),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Cansu",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 59",
                            Status = "Resident",
                            Surname = "Aslan",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6719)
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 6,
                            Email = "b.kaplan@gmail.com",
                            IdentityNumber = "89076741888",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6738),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Banu",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 60",
                            Status = "Resident",
                            Surname = "Kaplan",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6738)
                        },
                        new
                        {
                            Id = 7,
                            ApartmentId = 7,
                            Email = "h.atak@gmail.com",
                            IdentityNumber = "13060621122",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6755),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Hülya",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 61",
                            Status = "Resident",
                            Surname = "Atak",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 8,
                            ApartmentId = 8,
                            Email = "l.atak@gmail.com",
                            IdentityNumber = "25120656692",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6773),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Leyla",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 62",
                            Status = "Resident",
                            Surname = "Atak",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6773)
                        },
                        new
                        {
                            Id = 9,
                            ApartmentId = 9,
                            Email = "a.gul@gmail.com",
                            IdentityNumber = "53465893878",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6814),
                            IsActive = true,
                            IsDelete = false,
                            Name = "Aslı",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 63",
                            Status = "Resident",
                            Surname = "Gül",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6814)
                        },
                        new
                        {
                            Id = 10,
                            ApartmentId = 10,
                            Email = "i.yaylaci@gmail.com",
                            IdentityNumber = "55690108116",
                            InsertDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6832),
                            IsActive = true,
                            IsDelete = false,
                            Name = "İpek",
                            Password = "25b80b3556ca3a15353dd2fd312062fad27adcf5a1de51b75bdadea1fa8214ab",
                            PhoneNumber = "0555 555 55 64",
                            Status = "Resident",
                            Surname = "Yaylacı",
                            UpdateDate = new DateTime(2023, 8, 10, 4, 49, 20, 628, DateTimeKind.Local).AddTicks(6832)
                        });
                });

            modelBuilder.Entity("ApartmentUser", b =>
                {
                    b.HasOne("ResiPay.DB.Entities.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiPay.DB.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Bill", b =>
                {
                    b.HasOne("ResiPay.DB.Entities.Apartment", "Apartment")
                        .WithMany("Bills")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiPay.DB.Entities.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Card", b =>
                {
                    b.HasOne("ResiPay.DB.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Message", b =>
                {
                    b.HasOne("ResiPay.DB.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.Apartment", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("ResiPay.DB.Entities.User", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Cards");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
